version: "3"

services:
  db:
    image: mdillon/postgis
    container_name: visitor_database
    ports:
      - "5432:5432"
    volumes:
      - visitor_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=visitor_db
      - POSTGRES_USER=visitor_admin
      - POSTGRES_PASSWORD=admin123
    networks:
      - db_network

  graphql-engine:
    image: hasura/graphql-engine:v2.38.0
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
#      DJAPI_WEBHOOK_AUTH: 'Token a0c5541df4ba661c86cfae4f476f6230d795f43c'
      HASURA_GRAPHQL_DATABASE_URL: postgres://visitor_admin:admin123@db:5432/visitor_db
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: visitor_db
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"F8fmcyKmgcm8lZSIZoCbxCTPCW21Ej0C","claims_namespace":"user_claims","claims_format":"json"}'
    restart: always
    networks:
      - db_network

  graphql-data-connector:
    image: hasura/graphql-data-connector:v2.38.0
    container_name: data-connector-agent-1
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - db_network
      
networks:
  db_network:
    driver: bridge

volumes:
  visitor_db:
